ipython --pdb -- scripts/_6_make_aep_evoked.py --input_dir ~/dev/projects/IBIS-EEG/derivatives/autoreject/run-01                       

ipython --pdb -- scripts/get_peaks.py --method "mne" --derivative_fpath ./derivatives/evoked/run-01/ --session "12" --extrema "positive" --plot

ipython --pdb -- scripts/get_peaks.py --method "mne" --derivative_fpath ./derivatives/evoked/run-01/ --session "12" --extrema "positive" --plot